Data Digest
https://youtu.be/X5NXDK6AVtU

```{r}
library(tidyverse)
```


```{r}
# IQ distribution

iq <- rnorm(n = 200, mean = 100, sd = 15)

```
```{r}
x_norm <- seq(from = -3, to = 3, by = 0.1)
y_norm <- dnorm(x = seq(from = -3, to = 3, by = 0.1), mean = 0, sd = 1)

plot(x_norm, y_norm, type = "l")
```

pnorm cumulative prob

```{r}
pnorm(mean = 178, sd = 6, 180)
pnorm(q = c(160, 170, 178, 180, 190, 200), mean = 178, sd = 6)
pnorm(q = seq(from = -3, to = 3, by = 0.1))
pnorm(q = c(0.67, 1, 2, 2.5, 3), mean = 0, sd = 1)

pnorm(q = 190, mean = 178, sd = 6)
pnorm(q = 190, mean = 178, sd = 6) - pnorm(q = 170, mean = 178, sd = 6)
abs(pnorm(q = -2, mean = 0, sd = 1) - pnorm(q = -1, mean = 0, sd = 1))
```
qnorm

```{r}
qnorm(p = 0.99, mean = 178, sd = 6)
qnorm(p = 0.75, mean = 100, sd = 15)
```
```{r}
set.seed(1)

rnorm_df <- data.frame(r = rnorm(200, mean = 100, sd = 15),
                       value = 1:200, box = 100)

polygon_data <- data.frame(
  x = c(50, seq(from = 50, to = 150, by = 0.5), 150),
  y = c(0, dnorm(seq(from = 50, to = 150, by = 0.5),
                 mean = 100, sd = 15), 0))

r_plot <- rnorm_df|>
  ggplot() +
  geom_boxplot(aes(x = box, y = r),
               width = 50, alpha = 0.3,
               fill = "#9A3A3A", color = "#9A3A3A") +
  geom_point(aes(x = value, y = r),
             size = 2, alpha = 0.7, color = "#9A3A3A") +
  labs(x = "", y = "") +
  ggtitle(label = "norm(n=200, mean = 100, sd = 15)",
          subtitle = "generates random data")

r_plot
```
```{r}
d_plot <- data.frame(
  x = 50:150,
  y = dnorm(x = 50:150, mean = 100, sd = 15))|>
    ggplot( aes(x = x, y = y)) +
  geom_polygon(data = polygon_data,
           fill = "#4472C4",
           alpha = 0.3) +
    geom_line(size = 2,
              color = "#4472C4") +
    labs(x = "", y = "") +
    ggtitle(label = "dnorm()", subtitle = "creates the probability density function (PDF), \nwhere the area on the curve sums to 1.")

d_plot
```

pnorm graph
```{r}
pnorm_x <- 125
pnorm_y <- pnorm(q = pnorm_x, mean = 100, sd = 15)

p_plot <- data.frame(
  x = 50:150,
  y = pnorm(q = 50:150, mean = 100, sd = 15))|>
  ggplot(aes(x = x, y = y)) +
  geom_line(size = 2,
            color = "darkgreen") +
  labs(x = "", y = "") +
  scale_y_continuous(
    labels = scales::percent,
    breaks = c(0, 0.25, 0.5, 0.75, pnorm_y, 1)) +
  ggtitle(label = "pnorm()", subtitle = "tells you that with an IQ of 125\nyou are at the top 95.2%") +
  geom_segment(x = pnorm_x, xend = pnorm_x,
               y = -0.1, yend = pnorm_y,
               linetype = "dashed") +
  geom_segment(x = 40, xend = pnorm_x, y = pnorm_y, yend = pnorm_y, linetype = "dashed")

p_plot
```

qnorm plot
```{r}
qnorm_x <- 0.85
qnorm_y <- qnorm(p = qnorm_x, mean = 100, sd = 15)

q_plot <- data.frame(x = seq(from = 0, to = 1, by = 0.005),
                     y = qnorm(p = seq(from = 0, to = 1, by = 0.005), mean = 100, sd = 15))|>
  ggplot(aes(x = x, y = y)) +
  geom_line(size = 2, color = "orange") +
  labs(x = "", y = "") +
  scale_x_continuous(labels = scales::percent, breaks = c(0, .25, .5, .75, qnorm_x, 1)) +
  ggtitle(label = "qnorm()",
          subtitle = "tells you that if you want to be in the top 85%\nyou need an IQ of 116") +
  geom_segment(x = qnorm_x, xend = qnorm_x, y = 40, yend = qnorm_y, linetype = "dashed") +
  geom_segment(x = -0.1, xend = qnorm_x, y = qnorm_y, yend = qnorm_y, linetype = "dashed")

q_plot
```

