---
title: "06_lecture_04"
author: "Brandon Foltz"
date: "2023-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(swirl)
```


```{r manual_vector}
c(1,3,7,-0.5)
length(c(1,3,7,-0.5))
#can only contain one TYPE of data
```

```{r vector_math}
c(1,2,3) + c(4,5,6)
c(1,2,3,4)^3
```

```{r vector_recycling}
c(0.5,3) * c(1,2,3,4) #c(0.5*1, 3*2. 0.5*3, 3*4)
c(0.5, 3, 0.5, 3) * c(1,2,3,4)  #same thing
3 * c(-1,0,1,2) #scalar vector
3 * c(-1,0,1,2) + 1 #addition is elementwise also
c(1,2,3,4) +c(0.5, 1.5, 2.5) #c(1 +0.5, 2 + 1.5, 3 + 2.5, 4 + 0.5) recycled the shorter vector
```

```{r vector_wise_math}
sum(c(1,2,3,4,5))
max(c(1,2,3,4,5))
# can be used in summarize in dplyr
```

```{r example_standardizing_data}
grades <- c(97, 68, 75, 77, 69, 81, 80, 92, 50, 34, 66, 83, 52)
z_grades <- (grades - mean(grades))/sd(grades)
round(z_grades, 2)
round(scale(grades),2)
scale(1:10)
```

```{r generating_numeric_vectors}
seq(-3, 6, by = 1.75)
rep(c(-1,0,1), times =3) #the vector 3 times
rep(c(-1,0,1), each = 3) #each element 3 times
```

```{r integer_vectors}
1:12
12:4
class(9L)
```

```{r character_vector}
class(c("Andre", "Beth"))
```

```{r factor_vector}
factor(c("M", "F", "F", "M"))
# unique values the factor takes
as.numeric(factor(c("M", "F", "F", "M")))
```

```{r logical_vectors}
nchar(c("Brandon", "Brian"))
nchar(c("Brandon", "Brian")) >=6
mean(nchar(c("Brandon", "Brian")) >=6)
nchar(c("Brandon", "Brian")) %% 2 == 0
substr(c("Brandon", "Brian"), start = 2, stop = 2) == "r"
(nchar(c("Brandon", "Brian")) %% 2 == 0) & (substr(c("Brandon", "Brian"), start = 2, stop = 2) == "r")
(nchar(c("Brandon", "Brian")) %% 2 == 0) | (substr(c("Brandon", "Brian"), start = 2, stop = 2) == "r")
!(nchar(c("Brandon", "Brian")) %% 2 == 0) | (substr(c("Brandon", "Brian"), start = 2, stop = 2) == "r")
#subsetting
c("Brandon", "Brian")[c(1,2)]
"Brandon" %in% c("Brandon", "Brian")
which("Brandon" %in% c("Brandon", "Brian"))
```

```{r missing_values}
c(1,2,NA,4,5,6,NA)
length(c(1,2,NA,4,5,6,NA))
mean(c(1,2,NA,4,5,6,NA))
mean(c(1,2,NA,4,5,6,NA), na.rm = T)
is.na(c("Brandon", NA, "Brian"))
!is.na(c("Brandon", NA, "Brian"))
c(-2, -1, 0, 1, 2) / 0
is.finite(c(-2, -1, 0, 1, 2) / 0)
is.nan(c(-2, -1, 0, 1, 2) / 0)
```

```{r head_tail}
head(letters)
head(letters, 10)
tail(letters, 10)
```

```{r named_vectors}
a_vector <- 1:26
names(a_vector) <- LETTERS
head(a_vector)
a_vector[c("B","R","A","N","D","O","N")]
```

```{r matrices}
a_matrix <- matrix(letters[1:6], nrow = 2, ncol = 3)
a_matrix
b_matrix <- matrix(letters[1:6], nrow = 2, ncol = 3, byrow = TRUE)
b_matrix
c_matrix <- cbind(c(1,2), c(3,4), c(5,6))
c_matrix
d_matrix <- rbind(c(1,2,3), c(4,5,6))
d_matrix
a_matrix[1,2] #row 1 and column 2
a_matrix[1, c(2,3)] #row 1 intersect columns 2 and 3
dim(a_matrix)
length(a_matrix) #number of elements
a_matrix[ ,1] # all rows, column 1 becomes a VECTOR
a_matrix[ , 1, drop = FALSE] # all rows, column 1 stays a MATRIX
bad_matrix <- cbind(1:2, LETTERS[c(6,1)])
bad_matrix
typeof(bad_matrix)
rownames(bad_matrix) <- c("Wedge", "Biggs")
colnames(bad_matrix) <- c("Pilot Grade", "Mustache Grade")
bad_matrix
bad_matrix["Biggs", , drop = FALSE]
cbind(c_matrix, d_matrix)
c_matrix / d_matrix
e_matrix <- t(c_matrix) #transpose
e_matrix
f_matrix <- d_matrix %*% e_matrix #matrix multiplication
f_matrix
g_matrix <- solve(f_matrix)
g_matrix
f_matrix %*% g_matrix #floating point imprecision
diag(2)
diag(g_matrix)
```

```{r lists}
my_list <- list("first_thing" = 1:5,
                "second_thing" = matrix(8:11, nrow = 2),
                "third_thing" = lm(dist ~ speed, data = cars))
my_list
my_list[["first_thing"]]
my_list$first_thing
my_list[[1]]
# can hold pretty much anything without rules
str(my_list[1]) # gives a list
str(my_list[[1]]) # gives the stuff inside the list
length(my_list[c(1,2)])
str(my_list[c(1,2)])
str(my_list[[3]], list.len = 7) # all the STUFF created by linear regression
names(my_list[[3]]) #all the regression elements, all the goodies
str(cars) # dataframe where all variable lists have the same number of element
length(cars) # columns
length(cars$dist) # elements in the variables
cars[1, ] #row 1 all columns
cars[1:5, "speed", drop = FALSE] # first 5 rows of the speed column
```

```{r dplyr}
mean(swiss[swiss$Education > mean(swiss$Education), "Education"])

swiss %>%
  filter(Education > mean(Education)) %>%
  summarise(mean = mean(Education))
```

```{r}
swiss %>%
  select(2:3) %>%
  head()

swiss %>%
  select(2:3) %>%
  as_tibble(rownames = "Name") %>%
  head()
```

```{r pull_from_lm_object}
my_list[[3]][["coefficients"]]
speed_beta <- my_list[[3]][["coefficients"]]["speed"]
speed_beta
summary(my_list[[3]])
summary(my_list[[3]])["coefficients"]
speed_SE <- summary(my_list[[3]])[["coefficients"]]["speed", "Std. Error"] #go to coeff, get speed row and std error column
speed_SE
speed_CI <- speed_beta + c(-qnorm(0.975), qnorm(0.975)) * speed_SE
names(speed_CI)  <- c("lower", "upper")
speed_CI
```

A 1 mph increase in speed is associated with a `r round(speed_beta, 1)` ft. increase in stopping distance (95% CI: (`r round(speed_CI["lower"], 1)`, `r round(speed_CI["upper"], 1)`)).