---
title: "Lecture 7 - Vectorization and Functions"
author: "Brandon Foltz"
date: "2023-02-26"
output: html_document
---

https://youtu.be/Qq1VFydPlNw


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
```

```{r avoid_loops}
# built in vectorized functions help avoid loops; i.e. dplyr
colMeans(swiss)
# mean(), dplyr::filter(), readr::read_csv()
```

```{r}
# function that outputs the first and last values of a vector
first_and_last <- function(x) {
  first <- x[1]
  last <- x[length(x)]
  return(c("first" = first, "last" = last))
}

first_and_last(1:10)

# source() can load other R scripts and will run whatever is in them
```

```{r}
smarter_first_and_last <- function(x){
  if (length(x) == 0L) { # specify integers with L
    stop("The input has no length!")
  } else {
    first <- x[1]
  last <- x[length(x)]
  return(c("first" = first, "last" = last))
  }
}
```
Anatomy of a Function

NAME <- function(ARGUMENT1, ARGUMENT2 = DEFAULT){
BODY
RETURN(OUTPUT)
}

```{r}
quantile_report <- function(x, na.rm = FALSE){
  quants <- quantile(x, na.rm = na.rm,
                     probs = c(0.01, 0.05, 0.10, 0.25, 0.5, 0.75, 0.90, 0.95, 0.99))
  names(quants) <- c("Bottom 1%", "Bottom 5%", "Bottom 10%", "Bottom 25%", "Median", "Top 25%", "Top 10%", "Top 5%", "Top 1%")
  return(quants)
}

quantile_report(rnorm(10000))
```

```{r apply}
# apply() functions iterate over elements of objects
# sapply() turns output into a matrix and often looks better

lapply(swiss, FUN = quantile_report)
lapply(swiss, FUN = mean)
sapply(swiss, quantile_report)
sapply(swiss, mean)
apply(swiss, MARGIN = 2, quantile_report) #MARGIN 2 means columns, MARGIN 1 means rows

```

```{r}
loop_vec <- numeric(5)
for (x in seq_along(loop_vec)) {
  loop_vec[x]  <- x^2
}
loop_vec

apply_vec <- sapply(1:5, function(x){x^2})
apply_vec
```

```{r}
bucket <- function(x, quants = c(1/3, 2/3)){
  #set low extreme, quantile points, high extreme
  new_breaks <- c(min(x)-1, quantile(x, probs = quants), max(x)+1)
  #labels = FALSE will return integer codes instead of ranges
  return(cut(x, breaks = new_breaks, labels = FALSE))
}

dat <- rnorm(100)
dat_quants <- c(0.05, 0.25, 0.50, 0.75, 0.95)
bucketed_dat <- bucket(dat, quants = dat_quants)
plot(x = bucketed_dat, y = dat, main = "Buckets and values", pch = 16)
abline(h = quantile(dat, dat_quants), lty = "dashed", col = "red")

bucketed_dat_thirds <- bucket(dat) # uses the default of 1/3 and 2/3
plot(x = bucketed_dat_thirds, y = dat, main = "Buckets and values", pch = 16)
abline(h = quantile(dat), lty = "dashed", col = "red")
```

```{r impossible_data}
school_data <- 
  data.frame(school = letters[1:10],
             pr_passing_exam = c(0.78, 0.55, 0.91, -1, 0.88, 0.81, 0.90, 0.76, 99, 99),
             pr_free_lunch = c(0.33, 99, 0.25, 0.05, 0.12, 0.09, 0.22, -13, 0.21, 99))
school_data

# Goal: Remove extreme values
# Input: a vector x, cutoff for low and high
# Output: A vector with NA in the extreme places

remove_extremes <- function(x, low, high){
  x_no_low <- ifelse(x < low, NA, x)
  x_no_low_no_high <- ifelse(x_no_low > high, NA, x)
  return(x_no_low_no_high)
}

#remove_extremes(school_data$pr_passing_exam, low = 0, high = 1)

school_data %>%
  mutate(across(-school, ~ remove_extremes(x = ., low = 0, high = 1)))
```

```{r anonymous_functions}
swiss %>%
  summarise(across(everything(), ~ mean(. , na.rm = TRUE) / sd(. , na.rm = TRUE)))

lapply(swiss, function(x) mean(x, na.rm = TRUE) / sd(x, na.rm = TRUE))
```

```{r flexible_ggplot}
ggplot(gapminder %>%
         filter(country == "Afghanistan"),
       aes(x = year, y = pop / 10e6)) +
  geom_line(color = "firebrick") +
  xlab(NULL) +
  ylab("Population (millions)") +
  ggtitle("Population of Afghanistan since 1952") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0, size = 20))

gapminder_lifeplot  <- function(cntry){
  ggplot(gapminder %>%
           filter(country == cntry),
         aes(x = year, y = lifeExp)) +
    geom_line(color = "firebrick") +
    xlab(NULL) +
    ylab("Life Expectancy") +
    ggtitle(paste0("Life expectancy in ", cntry, " since 1952")) +
    theme(plot.title = element_text(hjust = 0, size = 20))
}

gapminder_lifeplot(cntry = "Turkey")
gapminder_lifeplot(cntry = "Rwanda")
```

```{r flexible_y_value}
y_axis_label <- c("lifeExp" = "Life expectancy",
                  "pop" = "Population (millions)",
                  "gdpPercap" = "GDP per capita, USD")
title_text <- c("lifeExp" = "Life expectancy in ",
                "pop" = "Population of ",
                "gdpPercap" = "GDP per capita in ")
y_axis_label["pop"]
title_text["pop"]
```

```{r more_flexible_plotting}
gapminder_plot <- function(cntry, yvar){
  y_axis_label <- c("lifeExp" = "Life expectancy",
                  "pop" = "Population (millions)",
                  "gdpPercap" = "GDP per capita, USD")[yvar]
title_text <- c("lifeExp" = "Life expectancy in ",
                "pop" = "Population of ",
                "gdpPercap" = "GDP per capita in ")[yvar]
ggplot(gapminder %>%
         filter(country == cntry) %>%
         mutate(pop = pop/10e6),
       aes_string(x = "year", y = yvar)) +
  geom_line(color = "firebrick") +
  ggtitle(paste0(title_text, cntry, " since 1952")) +
  xlab(NULL) +
  ylab(y_axis_label) +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0, size = 20))
}

gapminder_plot("Turkey", "pop")
gapminder_plot("Nigeria", "gdpPercap")
```

```{r %in%}
us_ca <- c("Canada", "United States")
gapminder %>%
  filter(country %in% us_ca) %>%
  distinct(country) %>%
  head(2)

# inverted
gapminder %>%
  filter(!country %in% us_ca) %>%
  distinct(country) %>%
  head(2)

`%!in%` <- Negate(`%in%`) # new operator created. Logical negation of a function is Negate()

gapminder %>%
  filter(country %!in% us_ca) %>%
  distinct(country) %>%
  head(2)
```

```{r debug}
debug(gapminder_plot)
undebug(gapminder_plot)
```

