---
title: 'Lecture 9: Mapping'
author: "Brandon Foltz"
date: "2023-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggmap)
library(ggrepel)
library(sf)
library(tidycensus)
#spd_raw <- read_csv("https://raw.githubusercontent.com/clanfear/CSSS508/master/Seattle_Police_Department_911_Incident_Response.csv")
```

```{r}
ggplot(spd_raw,
       aes(Longitude, Latitude)) +
  geom_point() +
  coord_fixed() + #squares things up
  ggtitle("Seattle Police Incidents",
          subtitle = "March 25, 2016") +
  theme_classic()
```

```{r}
qmplot(data = spd_raw,
       x = Longitude,
       y = Latitude,
       color = I("#342c5c"),
       alpha = I(0.5))
```

```{r}
qmplot(data = spd_raw,
       geom = "blank",
       x = Longitude,
       y = Latitude,
       maptype = "toner-lite",
       darken = 0.5) +
  stat_density2d(
    aes(fill = stat(level)),
    geom = "polygon",
    alpha = 0.2, color = NA) +
  scale_fill_gradient2(
    "Incident\nConcentration",
    low = "white",
    mid = "yellow",
    high = "red") +
  theme(legend.position = "bottom")
```

```{r}
downtown <- spd_raw %>%
  filter(Latitude > 47.58, Latitude < 47.64,
         Longitude > -122.36, Longitude < -122.31)

assaults <- downtown %>%
  filter(`Event Clearance Group` %in%
           c("ASSAULTS", "ROBBERY")) %>%
  rename(assault_label = `Event Clearance Description`)
```

```{r}
qmplot(data = downtown,
       x = Longitude,
       y = Latitude,
       maptype = "toner-lite",
       color = I("firebrick"),
       alpha = I(0.5)) +
  geom_label(data = assaults,
             aes(label = assault_label),
             size = 2)
```

```{r}
qmplot(
  data = downtown,
  x = Longitude,
  y = Latitude,
  maptype = "toner-lite",
  color = I("firebrick"),
  alpha = I(0.5)) +
  geom_label_repel(
    data = assaults,
    aes(label = assault_label),
    fill = "black",
    color = "white",
    segment.color = "black",
    size = 2)
```

```{r}
precinct_shape <- st_read("../data/district/votdst.shp") %>% 
  select(Precinct = NAME, geometry)
```
```{r}
precincts_votes_sf <- 
  read_csv("../data/king_county_elections_2016.txt") %>% 
  filter(Race == "US President & Vice President" &
           str_detect(Precinct, "SEA")) %>% 
  select(Precinct, CounterType, SumOfCount) %>% 
  group_by(Precinct) %>% 
  filter(CounterType %in%
           c("Donald J. Trump & Michael R. Pence",
             "Hillary Clinton & Tim Kaine",
             "Registered Voters",
             "Times Counted")) %>% 
  mutate(CounterType = 
           recode(CounterType,
                  "Donald J. Trump & Michael R. Pence" = "Trump",
                  "Hillary Clinton & Tim Kaine" = "Clinton",
                  "Registered Voters" = "RegisteredVoters",
                  "Times Counted" = "TotalVotes")) %>% 
  pivot_wider(names_from = CounterType,
              values_from = SumOfCount) %>% 
  mutate(P_Dem = Clinton / TotalVotes,
         P_Rep = Trump / TotalVotes,
         Turnout = TotalVotes / RegisteredVoters) %>% 
  select(Precinct, P_Dem, P_Rep, Turnout) %>% 
  filter(!is.na(P_Dem)) %>% 
  left_join(precinct_shape) %>%
  st_as_sf()
  
```

```{r}
ggplot(precincts_votes_sf,
       aes(fill = P_Dem)) +
  geom_sf(size = NA) +
  theme_void() +
  theme(legend.position = "bottom")
```

```{r}
acs_2015_vars <- load_variables(2015, "acs5")
acs_2015_vars[10:18,] %>% print()
```

```{r}
king_county <- 
  get_acs(geography = "tract",
          state = "WA",
          county = "King",
          geometry = TRUE,
          variables = c("B02001_001E",
                        "B02009_001E"),
          output = "wide")
```

```{r}
king_county <- king_county %>% 
  select(-ends_with("M")) %>% 
  rename(`Total Population` = B02001_001E,
         `Any Black` = B02009_001E) %>% 
  mutate(`Any Black` = `Any Black` / `Total Population`)
glimpse(king_county)
```

```{r}
king_county %>% 
  ggplot(aes(fill = `Any Black`)) +
  geom_sf(size = NA) +
  coord_sf(crs = "+proj=longlat +datum=WGS84", datum = NA) +
  scale_fill_continuous(name = "Any Black\n",
                        low = "#d4d5f9",
                        high = "#00025b") +
  theme_minimal() +
  ggtitle("Proportion Any Black")
```

```{r}
st_erase <- function(x ,y){
  st_difference(x, st_make_valid(st_union(st_combine(y))))
}
kc_water <- tigris::area_water("WA", "King", class = "sf")
kc_nowater <- king_county %>% 
  st_erase(kc_water)

```

```{r}
oh_ham <- 
  get_acs(geography = "tract",
          state = "OH",
          county = "Hamilton",
          geometry = TRUE,
          variables = c("B02001_001E",
                        "B02009_001E"),
          output = "wide") %>% 
  select(-ends_with("M")) %>% 
  rename(`Total Population` = B02001_001E,
         `Any Black` = B02009_001E) %>% 
  mutate(`Any Black` = `Any Black` / `Total Population`)
```


```{r}
oh_ham %>% 
  ggplot(aes(fill = `Any Black`)) +
  geom_sf(size = NA) +
  coord_sf(crs = "+proj=longlat +datum=WGS84", datum = NA) +
  scale_fill_continuous(name = "Any Black\n",
                        low = "#d4d5f9",
                        high = "#00025b") +
  theme_minimal() +
  ggtitle("Proportion Any Black")
```

```{r}
oh_state <- 
  get_acs(geography = "tract",
          state = "OH",
          geometry = TRUE,
          variables = c("B02001_001E",
                        "B02009_001E"),
          output = "wide") %>% 
  select(-ends_with("M")) %>% 
  rename(`Total Population` = B02001_001E,
         `Any Black` = B02009_001E) %>% 
  mutate(`Any Black` = `Any Black` / `Total Population`)
```

```{r}
oh_state %>% 
  ggplot(aes(fill = `Any Black`)) +
  geom_sf(size = NA) +
  coord_sf(crs = "+proj=longlat +datum=WGS84", datum = NA) +
  scale_fill_continuous(name = "Any Black\n",
                        low = "#d4d5f9",
                        high = "#00025b") +
  theme_minimal() +
  ggtitle("Proportion Any Black")
```

```{r}
urbans <- tigris::urban_areas(cb = TRUE, class = "sf")
glimpse(urbans)
```

